-- require("obsidian").setup{
-- 	workspaces = {
-- 		{
-- 		name = "notebook",
-- 		path = "~/notebook",
-- 		},
-- 	},
-- 	daily_notes = {
--     		folder = "dailies",
--     		date_format = "%Y-%m-%d",
--     		default_tags = { "daily-notes" },
--     		template = nil
--   	},
-- 
-- }
