[tools]
bat = "latest"
"cargo:difftastic" = "latest"
"cargo:mergiraf" = "latest"
"cargo:rlsp-yaml" = "latest"
"cargo:rsigma-lsp" = "latest"
eza = "latest"
fzf = "latest"
neovim = "latest"
python = "latest"
ripgrep = "latest"
rust = "latest"
uv = "latest"
zoxide = "latest"
